---
spring:
  profiles:
  - dev

test: hello application dev changed 4
test2: hello application test2 dev  changed 4


---
spring:
  profiles:
  - prod

test: hello application prod
test2: hello application test2 prod
