---
spring:
  profiles:
  - dev

test: hello application dev changed 5
test2: hello application test2 dev  changed 5


---
spring:
  profiles:
  - prod

test: hello application prod
test2: hello application test2 prod
