---
spring:
  profiles:
  - dev

test: hello application dev changed 6
test2: hello application test2 dev  changed 6


---
spring:
  profiles:
  - prod

test: hello application prod
test2: hello application test2 prod
