---
spring:
  profiles:
  - dev

test: hello application dev changed 2
test2: hello application test2 dev  changed 2


---
spring:
  profiles:
  - prod

test: hello application prod
test2: hello application test2 prod
