---
spring:
  profiles:
  - dev

test: hello application dev changed
test2: hello application test2 dev  changed


---
spring:
  profiles:
  - prod

test: hello application prod
test2: hello application test2 prod
